### ISSUE TITLE
Retorno Files

### ISSUE THREAD

**Issue by EzequielMessore** [duduribeiro/uniara_virtual_api#3]
Boa Tarde, Se em vez de você retornar "COORDENAÇÃO" etc (Nome das Disciplinas) ... você retornasse uma chave genérica ex.: "Discipline". acho que melhoraria o tratamento.

**Comment by duduribeiro** [comment]
@EzequielMessore de uma olhada no PR #4 para ver se te atende. Faça os testes. Se sim, feche a issue dps ;).

Tente implementar no mobile:
thiago-sydow/uniaravirtual-app#2 - issue referente

thanks

:beers:

**Comment by EzequielMessore** [comment]
Perfeito @duduribeiro deu tudo certo. Obrigado!
